# Generated by Django 4.0.3 on 2022-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('R', 'Rubles'), ('E', 'Euro'), ('D', 'Dollars')], default='', max_length=1),
        ),
    ]
