# Generated by Django 4.0.3 on 2022-04-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('R', 'Rubles'), ('E', 'Euro'), ('D', 'Dollars')], default='Dollars', max_length=1),
        ),
    ]
